=== UO300619/sew/xml/circuito.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.uniovi.es"
xmlns="http://www.uniovi.es"
elementFormDefault="qualified">
	<xs:element name="circuito">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="nombreC" />
				<xs:element ref="longitud" />
				<xs:element ref="anchura" />
				<xs:element ref="fecha" />
				<xs:element ref="hora" />
				<xs:element ref="numeroVueltas" />
				<xs:element ref="localidad" />
				<xs:element ref="pais" />
				<xs:element ref="patrocinador" />
				<xs:element ref="referencias" />
				<xs:element ref="imagenes" />
				<xs:element ref="videos" />
				<xs:element ref="origen" />
				<xs:element ref="tramos" />
				<xs:element ref="vencedor" />
				<xs:element ref="clasificados" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="nombreC">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nombre" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="longitud">
		<xs:complexType>
			<xs:attribute name="metros" type="xs:decimal" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="anchura">
		<xs:complexType>
			<xs:attribute name="metros" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="fecha">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="dia" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="hora">
  		<xs:complexType>
    		<xs:attribute name="hora" type="xs:time" use="required"/>
  		</xs:complexType>
	</xs:element>
	<xs:element name="numeroVueltas">
		<xs:complexType>
			<xs:attribute name="vueltas" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="localidad">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="ciudad" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="pais">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="pais" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="patrocinador">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="empresa" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencias">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="unbounded" ref="referencia" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="referencia">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="url" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagenes">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" maxOccurs="5" ref="imagen" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="imagen">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="url" type="xs:string" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="videos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="video" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="video">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="url" type="xs:string" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="origen">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramos">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="0" maxOccurs="unbounded" ref="tramo" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="tramo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="coordenada" />
			</xs:sequence>
			<xs:attribute name="longitud" type="xs:decimal" use="required" />
			<xs:attribute name="numeroSector" type="xs:integer" use="required" />
		</xs:complexType>
	</xs:element>
	<xs:element name="numeroSector" type="xs:integer" />
	<xs:element name="coordenada">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="latitud" type="latitudType" use="required" />
					<xs:attribute name="longitud" type="longitudType" use="required" />
					<xs:attribute name="altitud" type="altitudType" use="required"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:element name="vencedor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="persona" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="clasificados">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="3" maxOccurs="3" ref="persona" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="persona">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="nombre" type="xs:string" use="required" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="latitudType">
  		<xs:restriction base="xs:decimal">
    		<xs:minInclusive value="-90"/>
    		<xs:maxInclusive value="90"/>
  		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="longitudType">
  		<xs:restriction base="xs:decimal">
    		<xs:minInclusive value="-20"/>
    		<xs:maxInclusive value="20"/>
  		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="altitudType">
  		<xs:restriction base="xs:integer">
    		<xs:minInclusive value="0"/>
    		<xs:maxInclusive value="1000"/>
  		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== UO300619/sew/xml/circuitoEsquema.xml
<?xml version="1.0" encoding="UTF-8"?>
<circuito 
    xmlns="http://www.uniovi.es"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uniovi.es circuito.xsd">
    
    <nombreC nombre="Automotodrom Brno"></nombreC>
    <longitud metros="5.403"></longitud>
    <anchura metros="15"></anchura>
    <fecha dia="del 18 al 20 de julio"></fecha>
    <hora hora="14:00:00"></hora>
    <numeroVueltas vueltas="21"></numeroVueltas>
    <localidad ciudad="Brno"></localidad>
    <pais pais="Chequia"></pais>
    <patrocinador empresa="Tissot"></patrocinador>
    <referencias>
        <referencia url="https://www.automotodrombrno.cz/en">Sitio oficial</referencia>
        <referencia url="https://www.motogpbrno.com/es">Otra referencia</referencia>
        <referencia url="https://www.dazn.com/es-ES/news/motor/circuito-brno-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-republica-checa-mundial-motogp/83vt46p8sj0i1g3wdcmgk6gmb">Otra referencia</referencia>
    </referencias>
    <imagenes>
        <imagen url="MotoGP-Desktop/multimedia/BRNO">Circuito General</imagen>
        <imagen url="MotoGP-Desktop/multimedia/esquemaBRNO">Mapa del circuito</imagen>
        <imagen url="MotoGP-Desktop/multimedia/gradasBRNO">Gradas</imagen>
    </imagenes>
    <videos>
        <video url="MotoGP-Desktop/multimedia/BRNO2015">Circuito en 2015</video>
    </videos>
    <origen>
        <coordenada latitud="49.20278" longitud="16.44528" altitud="440"></coordenada>
    </origen>
    <tramos>
    <tramo longitud="619.39" numeroSector="1">
        <coordenada latitud="49.20333" longitud="16.44583" altitud="440"/>
    </tramo>
    <tramo longitud="245.39" numeroSector="1">
        <coordenada latitud="49.20611" longitud="16.44056" altitud="438"/>
    </tramo>
    <tramo longitud="164.79" numeroSector="1">
        <coordenada latitud="49.20556" longitud="16.44278" altitud="438"/>
    </tramo>
    <tramo longitud="503.43" numeroSector="2">
        <coordenada latitud="49.20583" longitud="16.44972" altitud="446"/>
    </tramo>
    <tramo longitud="116.09" numeroSector="2">
        <coordenada latitud="49.20667" longitud="16.45056" altitud="449"/>
    </tramo>
    <tramo longitud="121.6" numeroSector="2">
        <coordenada latitud="49.20778" longitud="16.45" altitud="450"/>
    </tramo>
    <tramo longitud="102.54" numeroSector="2">
        <coordenada latitud="49.20833" longitud="16.45083" altitud="449"/>
    </tramo>
    <tramo longitud="459.64" numeroSector="2">
        <coordenada latitud="49.20917" longitud="16.45667" altitud="430"/>
    </tramo>
    <tramo longitud="562.69" numeroSector="3">
        <coordenada latitud="49.20611" longitud="16.45611" altitud="423"/>
    </tramo>
    <tramo longitud="412.11" numeroSector="3">
        <coordenada latitud="49.20611" longitud="16.46028" altitud="406"/>
    </tramo>
    <tramo longitud="496.13" numeroSector="3">
        <coordenada latitud="49.20250" longitud="16.46417" altitud="387"/>
    </tramo>
    <tramo longitud="170.76" numeroSector="3">
        <coordenada latitud="49.20167" longitud="16.46306" altitud="379"/>
    </tramo>
    <tramo longitud="259.98" numeroSector="3">
        <coordenada latitud="49.20278" longitud="16.46" altitud="384"/>
    </tramo>
    <tramo longitud="264.36" numeroSector="3">
        <coordenada latitud="49.20194" longitud="16.45722" altitud="404"/>
    </tramo>
    <tramo longitud="485.48" numeroSector="1">
        <coordenada latitud="49.20333" longitud="16.45111" altitud="437"/>
    </tramo>
    <tramo longitud="375.78" numeroSector="1">
        <coordenada latitud="49.20222" longitud="16.44722" altitud="441"/>
    </tramo>
</tramos>
    <vencedor>
        <persona nombre="Marc Marquez"></persona>
    </vencedor>
    <clasificados>
        <persona nombre="Marc Marquez"></persona>
        <persona nombre="Pedro Acosta"></persona>
        <persona nombre="Enea Bastianini"></persona>
    </clasificados>
</circuito>
