=== UO300619/sew/xml/circuito.dtd
<!ELEMENT circuito (nombreC, longitud, anchura, fecha, hora,numeroVueltas,localidad,pais,patrocinador,referencias,imagenes,videos,origen,tramos,vencedor,clasificados)>
<!ELEMENT nombreC (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT anchura (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT numeroVueltas (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT patrocinador (#PCDATA)>
<!ELEMENT referencias (referencia*)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT imagenes (imagen*)>
<!ELEMENT imagen (#PCDATA)>
<!ELEMENT videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ELEMENT origen (coordenada)>
<!ELEMENT tramos (tramo*)>
<!ELEMENT tramo (coordenada)>
<!ELEMENT numeroSector (#PCDATA)>
<!ELEMENT coordenada (#PCDATA)>
<!ELEMENT vencedor (persona)>
<!ELEMENT clasificados (persona*)>
<!ELEMENT persona (#PCDATA)>
<!ATTLIST nombreC nombre CDATA #REQUIRED>
<!ATTLIST longitud unidad CDATA #REQUIRED>
<!ATTLIST anchura unidad CDATA #REQUIRED>
<!ATTLIST fecha dia CDATA #REQUIRED>
<!ATTLIST hora hora CDATA #REQUIRED>
<!ATTLIST numeroVueltas vueltas CDATA #REQUIRED>
<!ATTLIST localidad ciudad CDATA #REQUIRED>
<!ATTLIST pais pais CDATA #REQUIRED>
<!ATTLIST patrocinador empresa CDATA #REQUIRED>
<!ATTLIST referencia url CDATA #IMPLIED>
<!ATTLIST imagen url CDATA #IMPLIED>
<!ATTLIST video url CDATA #IMPLIED>
<!ATTLIST coordenada latitud CDATA #REQUIRED>
<!ATTLIST coordenada longitud CDATA #REQUIRED>
<!ATTLIST coordenada altitud CDATA #IMPLIED>
<!ATTLIST tramo longitud CDATA #REQUIRED>
<!ATTLIST tramo numeroSector CDATA #REQUIRED>
<!ATTLIST persona nombre CDATA #REQUIRED>

=== UO300619/sew/xml/circuito.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE circuito SYSTEM "circuito.dtd">
<circuito>
    <nombreC nombre="Automotodrom Brno"></nombreC>
    <longitud unidad="5.403 metros"></longitud>
    <anchura unidad="15 metros"></anchura>
    <fecha dia="del 18 al 20 de julio"></fecha>
    <hora hora="14:00"></hora>
    <numeroVueltas vueltas="21"></numeroVueltas>
    <localidad ciudad="Brno"></localidad>
    <pais pais="Chequia"></pais>
    <patrocinador empresa="Tissot"></patrocinador>
    <referencias>
        <referencia url="https://www.automotodrombrno.cz/en">Sitio oficial</referencia>
        <referencia url="https://www.motogpbrno.com/es">Otra referencia</referencia>
        <referencia url="https://www.dazn.com/es-ES/news/motor/circuito-brno-donde-esta-como-es-caracteristicas-como-llegar-fotos-escenario-gp-republica-checa-mundial-motogp/83vt46p8sj0i1g3wdcmgk6gmb">Otra referencia</referencia>
    </referencias>
    <imagenes>
        <imagen url="multimedia/BRNO">Circuito General</imagen>
        <imagen url="multimedia/esquemaBRNO">Mapa del circuito</imagen>
        <imagen url="multimedia/gradasBRNO">Gradas</imagen>
    </imagenes>
    <videos>
        <video url="multimedia/BRNO2015">Circuito en 2015</video>
    </videos>
    <origen>
        <coordenada latitud="49°12'10''N" longitud="16°26'43''E" altitud="440m"></coordenada>
    </origen>
    <tramos>
    <tramo longitud="619,39" numeroSector="1">
        <coordenada latitud="49°12'12''N" longitud="16°26'45''E" altitud="440"/>
    </tramo>
    <tramo longitud="245,39" numeroSector="1">
        <coordenada latitud="49°12'22''N" longitud="16°26'26''E" altitud="438"/>
    </tramo>
    <tramo longitud="164,79" numeroSector="1">
        <coordenada latitud="49°12'20''N" longitud="16°26'34''E" altitud="438"/>
    </tramo>
    <tramo longitud="503,43" numeroSector="2">
        <coordenada latitud="49°12'21''N" longitud="16°26'59''E" altitud="446"/>
    </tramo>
    <tramo longitud="116,09" numeroSector="2">
        <coordenada latitud="49°12'24''N" longitud="16°27'02''E" altitud="449"/>
    </tramo>
    <tramo longitud="121,6" numeroSector="2">
        <coordenada latitud="49°12'28''N" longitud="16°27'00''E" altitud="450"/>
    </tramo>
    <tramo longitud="102,54" numeroSector="2">
        <coordenada latitud="49°12'30''N" longitud="16°27'03''E" altitud="449"/>
    </tramo>
    <tramo longitud="459,64" numeroSector="2">
        <coordenada latitud="49°12'33''N" longitud="16°27'24''E" altitud="430"/>
    </tramo>
    <tramo longitud="562,69" numeroSector="3">
        <coordenada latitud="49°12'22''N" longitud="16°27'22''E" altitud="423"/>
    </tramo>
    <tramo longitud="412,11" numeroSector="3">
        <coordenada latitud="49°12'22''N" longitud="16°27'37''E" altitud="406"/>
    </tramo>
    <tramo longitud="496,13" numeroSector="3">
        <coordenada latitud="49°12'09''N" longitud="16°27'51''E" altitud="387"/>
    </tramo>
    <tramo longitud="170,76" numeroSector="3">
        <coordenada latitud="49°12'06''N" longitud="16°27'47''E" altitud="379"/>
    </tramo>
    <tramo longitud="259,98" numeroSector="3">
        <coordenada latitud="49°12'10''N" longitud="16°27'36''E" altitud="384"/>
    </tramo>
    <tramo longitud="264,36" numeroSector="3">
        <coordenada latitud="49°12'07''N" longitud="16°27'26''E" altitud="404"/>
    </tramo>
    <tramo longitud="485,48" numeroSector="1">
        <coordenada latitud="49°12'12''N" longitud="16°27'04''E" altitud="437"/>
    </tramo>
    <tramo longitud="375,78" numeroSector="1">
        <coordenada latitud="49°12'08''N" longitud="16°26'50''E" altitud="441"/>
    </tramo>
</tramos>
    <vencedor>
        <persona nombre="Marc Marquez"></persona>
    </vencedor>
    <clasificados>
        <persona nombre="Marc Marquez"></persona>
        <persona nombre="Pedro Acosta"></persona>
        <persona nombre="Enea Bastianini"></persona>
    </clasificados>
</circuito>
